---
# tasks file for hostname

- name: Apply hostname
  hostname:
    name: "{{ hostname }}"
  tags:
    - config
    - hostname

- name: Re-gather facts
  when: ansible_hostname != hostname_fqdn
  action: setup
  tags:
    - config
    - hostname

- name: Change the hostname
  copy:
    content: "{{ hostname }}{{ '\n' }}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  tags:
    - config
    - hostname

- name: Build hosts file
  template:
    src: "hosts.j2"
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags:
    - config
    - hostname

- name: Build mailname file
  copy:
    content: "{{ hostname_fqdn }}{{ '\n' }}"
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
  tags:
    - config
    - hostname
